---
- name: Check if all mandatory variables exist
  assert:
    that:
      - mail_docker_image|length > 0
      - mail_docker_tag|length > 0
      - mail_domains|length > 0
      - mail_persist_folder|length > 0
      - mail_accounts|length > 0
      - mail_cert_email|length > 0
      - mail_cert_image == "certbot/certbot"
      - mail_cert_tag|length > 0
      - mail_dkim_size is regex("1024|2048|4096")

- name: Check account variable
  assert:
    # TODO: Disable verbose output to avoid show of sensitive data to output
    quiet: yes
    that:
      - item.username|length > 0
      - item.domain|length > 0
      - item.password|length > 0
  with_items:
    - "{{ mail_accounts }}"

- name: Check account.restrict
  assert:
    # TODO: Disable verbose output to avoid show of sensitive data to output
    quiet: yes
    that:
      - item.1 is regex("send|receive")
  with_subelements:
    - "{{ mail_accounts }}"
    - "restrict"
